inherit_gem:
  rubocop-rails-omakase: rubocop.yml

require:
  - rubocop-rspec
  - rubocop-rails
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-rspec_rails
  - rubocop-performance
AllCops:
  NewCops: enable
  Exclude:
    - "bin/**/*"
    - "db/schema.rb"
    - "config/**/*"
    - "node_modules/**/*"
    - "vendor/**/*"
Style/Documentation: # Checks for missing top-level documentation of classes and modules
  Enabled: false
Rails/FilePath: # This cop is used to identify usages of file path joining process
  EnforcedStyle: arguments
RSpec/MessageSpies: # Checks that message expectations are set using spies
  Enabled: false
RSpec/ExampleLength: # Checks for long examples.
  Exclude:
    - "spec/features/*"
Layout/LineLength:
  AllowedPatterns:
    - !ruby/regexp /\A *# /
  Max: 150
RSpec/ContextWording:
  AllowedPatterns:
    - когда
FactoryBot/ExcessiveCreateList:
  MaxAmount: 12
Naming/AsciiIdentifiers:
  Exclude:
    - "features/**/*"
Metrics/AbcSize:
  Exclude:
    - "db/migrate/**/*"
Metrics/MethodLength:
  Exclude:
    - "db/migrate/**/*"
Style/FrozenStringLiteralComment:
  EnforcedStyle: never
