# Правила для составления элементов меню боковой панели:

# 1. Ключ локализации (i18_key):
#    Указан символический ключ для локализации, который будет использоваться для перевода имени пункта меню.
#    Пример: `:articles` – для локализации в YAML файле: `menu_items.articles`.

# 2. Иконка (icon):
#    Указывается название иконки, которая будет отображаться рядом с названием пункта меню.
#    Пример: `Tasks`, `icon`.

# 3. Политика доступа (policy):
#    Определяет модель или ресурс, к которому привязан пункт меню. Для проверки прав доступа используется Pundit.
#    Пример: `:article_version` – означает, что пункт меню доступен, если пользователь имеет доступ к этому
#    ресурсу через Pundit.

# 4. Путь (path_helper):
#    Путь к странице задается с использованием хелпера маршрутов, который генерирует URL.
#    Пример: `:articles_article_versions_path` – генерирует путь к разделу версий статей.

# 5. Контроллер (controller):
#    Указывает контроллер, связанный с пунктом меню, для проверки, активен ли этот пункт.
#    Пример: `:article_versions` – контроллер для версии статей.

# 6. Группа (group):
#    Элементы меню могут быть сгруппированы в разные секции, такие как `general` (основное меню)
#    или `admin` (административное меню).
#    Пример: `group: :general` – означает, что пункт меню относится к основной группе.

# 7. Действие (action): (опционально)
#    Если у пункта меню есть конкретное действие (например, `show`, `index`), оно также может быть указано
#    для определения активного состояния.
#    Пример: если `action: 'index'`, то пункт меню будет активен при выполнении действия `index` в контроллере.

# 8. Ошибки маршрутизации и политики:
#    Если хелпер маршрута или политика доступа не определены, ошибки логируются с сообщением,
#    помогающим диагностировать проблему.menu_items:

# Конфигурация для бокового меню на сайте
menu_items:
  # Группа элементов раздела "Основное меню"
  - i18_key: :articles
    icon: 'newspaper'
    policy: :book
    path_helper: :books_path
    controller: :books
    group: :general

